# Generated by Django 4.2.6 on 2023-10-16 19:34

from django.db import migrations, models
import django_bm25.indexes
import django_bm25.mixins


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ibge', '0001_auto_20231015_1903'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=7, unique=True, verbose_name='Code')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('state', models.CharField(max_length=2, verbose_name='State')),
            ],
            options={
                'verbose_name': 'City',
                'verbose_name_plural': 'Cities',
                'indexes': [django_bm25.indexes.Bm25Index(boolean_fields={}, json_fields={}, name='idx_search_city', numeric_fields={}, text_fields={'name': {'normalizer': 'lowercase', 'tokenizer': 'whitespace'}})],
            },
            bases=(django_bm25.mixins.FullTextSearchMixin, models.Model),
        ),
    ]
