# Generated by Django 4.2.6 on 2023-10-15 20:43

from django.db import migrations
import django_bm25.indexes
import example.ibge.models


class Migration(migrations.Migration):

    dependencies = [
        ('ibge', '0003_auto_20231015_1909'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='city',
            index=django_bm25.indexes.Bm25Index(example.ibge.models.Star(), boolean_fields={}, json_fields={}, name='idx_city_name', numeric_fields={}, text_fields={'name': {}}),
        ),
    ]
